artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ragalahariakula/datasets/raw/main/vifd.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/insurance fraud claims.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_validation/cleaned_data.csv

model_trainer:
  root_dir: artifacts/model_trainer
  X_train_data_path: artifacts/data_transformation/balanced_split_X_train.csv
  y_train_data_path: artifacts/data_transformation/balanced_split_y_train.csv
  X_test_data_path: artifacts/data_transformation/split_X_train.csv
  y_test_data_path: artifacts/data_transformation/split_y_train.csv
  model_name: model.joblib
  